version: "3.3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: asoebi-react-1.0.0
    container_name: asoebi-react
    command: npm start
