export const REASONS = [
    "Family & Friend support",
    "Tuition fee",
    "Rents",
    "Utility Bill Payment",
    "Hospital Bill",
    "Ceremonies",
    "Sending to self",
    "Airtime",
    "Debt repayment",
    "Construction project",
    "Njangi",
    "Other"
];

export const maxTransfersUnverified: any = {
  GBP: 800,
  CAD: Number.MAX_SAFE_INTEGER,
  EUR: Number.MAX_SAFE_INTEGER
}

export const currencySymbols: any = {
  GBP: "£",
  CAD: "CA$",
  EUR: "€"
}

export interface CountryType {
  countryCode: string;
  name: string;
  phoneCode: string;
}
// From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
const countriesAndCodes: readonly CountryType[] = [
  { countryCode: 'AD', name: 'Andorra', phoneCode: '376' },
  {
    countryCode: 'AE',
    name: 'United Arab Emirates',
    phoneCode: '971',
  },
  { countryCode: 'AF', name: 'Afghanistan', phoneCode: '93' },
  {
    countryCode: 'AG',
    name: 'Antigua and Barbuda',
    phoneCode: '1-268',
  },
  { countryCode: 'AI', name: 'Anguilla', phoneCode: '1-264' },
  { countryCode: 'AL', name: 'Albania', phoneCode: '355' },
  { countryCode: 'AM', name: 'Armenia', phoneCode: '374' },
  { countryCode: 'AO', name: 'Angola', phoneCode: '244' },
  { countryCode: 'AQ', name: 'Antarctica', phoneCode: '672' },
  { countryCode: 'AR', name: 'Argentina', phoneCode: '54' },
  { countryCode: 'AS', name: 'American Samoa', phoneCode: '1-684' },
  { countryCode: 'AT', name: 'Austria', phoneCode: '43' },
  {
    countryCode: 'AU',
    name: 'Australia',
    phoneCode: '61',
  },
  { countryCode: 'AW', name: 'Aruba', phoneCode: '297' },
  { countryCode: 'AX', name: 'Alland Islands', phoneCode: '358' },
  { countryCode: 'AZ', name: 'Azerbaijan', phoneCode: '994' },
  {
    countryCode: 'BA',
    name: 'Bosnia and Herzegovina',
    phoneCode: '387',
  },
  { countryCode: 'BB', name: 'Barbados', phoneCode: '1-246' },
  { countryCode: 'BD', name: 'Bangladesh', phoneCode: '880' },
  { countryCode: 'BE', name: 'Belgium', phoneCode: '32' },
  { countryCode: 'BF', name: 'Burkina Faso', phoneCode: '226' },
  { countryCode: 'BG', name: 'Bulgaria', phoneCode: '359' },
  { countryCode: 'BH', name: 'Bahrain', phoneCode: '973' },
  { countryCode: 'BI', name: 'Burundi', phoneCode: '257' },
  { countryCode: 'BJ', name: 'Benin', phoneCode: '229' },
  { countryCode: 'BL', name: 'Saint Barthelemy', phoneCode: '590' },
  { countryCode: 'BM', name: 'Bermuda', phoneCode: '1-441' },
  { countryCode: 'BN', name: 'Brunei Darussalam', phoneCode: '673' },
  { countryCode: 'BO', name: 'Bolivia', phoneCode: '591' },
  { countryCode: 'BR', name: 'Brazil', phoneCode: '55' },
  { countryCode: 'BS', name: 'Bahamas', phoneCode: '1-242' },
  { countryCode: 'BT', name: 'Bhutan', phoneCode: '975' },
  { countryCode: 'BV', name: 'Bouvet Island', phoneCode: '47' },
  { countryCode: 'BW', name: 'Botswana', phoneCode: '267' },
  { countryCode: 'BY', name: 'Belarus', phoneCode: '375' },
  { countryCode: 'BZ', name: 'Belize', phoneCode: '501' },
  {
    countryCode: 'CA',
    name: 'Canada',
    phoneCode: '1',
  },
  {
    countryCode: 'CC',
    name: 'Cocos (Keeling) Islands',
    phoneCode: '61',
  },
  {
    countryCode: 'CD',
    name: 'Congo, Democratic Republic of the',
    phoneCode: '243',
  },
  {
    countryCode: 'CF',
    name: 'Central African Republic',
    phoneCode: '236',
  },
  {
    countryCode: 'CG',
    name: 'Congo, Republic of the',
    phoneCode: '242',
  },
  { countryCode: 'CH', name: 'Switzerland', phoneCode: '41' },
  { countryCode: 'CI', name: "Cote d'Ivoire", phoneCode: '225' },
  { countryCode: 'CK', name: 'Cook Islands', phoneCode: '682' },
  { countryCode: 'CL', name: 'Chile', phoneCode: '56' },
  { countryCode: 'CM', name: 'Cameroon', phoneCode: '237' },
  { countryCode: 'CN', name: 'China', phoneCode: '86' },
  { countryCode: 'CO', name: 'Colombia', phoneCode: '57' },
  { countryCode: 'CR', name: 'Costa Rica', phoneCode: '506' },
  { countryCode: 'CU', name: 'Cuba', phoneCode: '53' },
  { countryCode: 'CV', name: 'Cape Verde', phoneCode: '238' },
  { countryCode: 'CW', name: 'Curacao', phoneCode: '599' },
  { countryCode: 'CX', name: 'Christmas Island', phoneCode: '61' },
  { countryCode: 'CY', name: 'Cyprus', phoneCode: '357' },
  { countryCode: 'CZ', name: 'Czech Republic', phoneCode: '420' },
  {
    countryCode: 'DE',
    name: 'Germany',
    phoneCode: '49',
  },
  { countryCode: 'DJ', name: 'Djibouti', phoneCode: '253' },
  { countryCode: 'DK', name: 'Denmark', phoneCode: '45' },
  { countryCode: 'DM', name: 'Dominica', phoneCode: '1-767' },
  {
    countryCode: 'DO',
    name: 'Dominican Republic',
    phoneCode: '1-809',
  },
  { countryCode: 'DZ', name: 'Algeria', phoneCode: '213' },
  { countryCode: 'EC', name: 'Ecuador', phoneCode: '593' },
  { countryCode: 'EE', name: 'Estonia', phoneCode: '372' },
  { countryCode: 'EG', name: 'Egypt', phoneCode: '20' },
  { countryCode: 'EH', name: 'Western Sahara', phoneCode: '212' },
  { countryCode: 'ER', name: 'Eritrea', phoneCode: '291' },
  { countryCode: 'ES', name: 'Spain', phoneCode: '34' },
  { countryCode: 'ET', name: 'Ethiopia', phoneCode: '251' },
  { countryCode: 'FI', name: 'Finland', phoneCode: '358' },
  { countryCode: 'FJ', name: 'Fiji', phoneCode: '679' },
  {
    countryCode: 'FK',
    name: 'Falkland Islands (Malvinas)',
    phoneCode: '500',
  },
  {
    countryCode: 'FM',
    name: 'Micronesia, Federated States of',
    phoneCode: '691',
  },
  { countryCode: 'FO', name: 'Faroe Islands', phoneCode: '298' },
  {
    countryCode: 'FR',
    name: 'France',
    phoneCode: '33',
  },
  { countryCode: 'GA', name: 'Gabon', phoneCode: '241' },
  { countryCode: 'GB', name: 'United Kingdom', phoneCode: '44' },
  { countryCode: 'GD', name: 'Grenada', phoneCode: '1-473' },
  { countryCode: 'GE', name: 'Georgia', phoneCode: '995' },
  { countryCode: 'GF', name: 'French Guiana', phoneCode: '594' },
  { countryCode: 'GG', name: 'Guernsey', phoneCode: '44' },
  { countryCode: 'GH', name: 'Ghana', phoneCode: '233' },
  { countryCode: 'GI', name: 'Gibraltar', phoneCode: '350' },
  { countryCode: 'GL', name: 'Greenland', phoneCode: '299' },
  { countryCode: 'GM', name: 'Gambia', phoneCode: '220' },
  { countryCode: 'GN', name: 'Guinea', phoneCode: '224' },
  { countryCode: 'GP', name: 'Guadeloupe', phoneCode: '590' },
  { countryCode: 'GQ', name: 'Equatorial Guinea', phoneCode: '240' },
  { countryCode: 'GR', name: 'Greece', phoneCode: '30' },
  {
    countryCode: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    phoneCode: '500',
  },
  { countryCode: 'GT', name: 'Guatemala', phoneCode: '502' },
  { countryCode: 'GU', name: 'Guam', phoneCode: '1-671' },
  { countryCode: 'GW', name: 'Guinea-Bissau', phoneCode: '245' },
  { countryCode: 'GY', name: 'Guyana', phoneCode: '592' },
  { countryCode: 'HK', name: 'Hong Kong', phoneCode: '852' },
  {
    countryCode: 'HM',
    name: 'Heard Island and McDonald Islands',
    phoneCode: '672',
  },
  { countryCode: 'HN', name: 'Honduras', phoneCode: '504' },
  { countryCode: 'HR', name: 'Croatia', phoneCode: '385' },
  { countryCode: 'HT', name: 'Haiti', phoneCode: '509' },
  { countryCode: 'HU', name: 'Hungary', phoneCode: '36' },
  { countryCode: 'ID', name: 'Indonesia', phoneCode: '62' },
  { countryCode: 'IE', name: 'Ireland', phoneCode: '353' },
  { countryCode: 'IL', name: 'Israel', phoneCode: '972' },
  { countryCode: 'IM', name: 'Isle of Man', phoneCode: '44' },
  { countryCode: 'IN', name: 'India', phoneCode: '91' },
  {
    countryCode: 'IO',
    name: 'British Indian Ocean Territory',
    phoneCode: '246',
  },
  { countryCode: 'IQ', name: 'Iraq', phoneCode: '964' },
  {
    countryCode: 'IR',
    name: 'Iran, Islamic Republic of',
    phoneCode: '98',
  },
  { countryCode: 'IS', name: 'Iceland', phoneCode: '354' },
  { countryCode: 'IT', name: 'Italy', phoneCode: '39' },
  { countryCode: 'JE', name: 'Jersey', phoneCode: '44' },
  { countryCode: 'JM', name: 'Jamaica', phoneCode: '1-876' },
  { countryCode: 'JO', name: 'Jordan', phoneCode: '962' },
  {
    countryCode: 'JP',
    name: 'Japan',
    phoneCode: '81',
  },
  { countryCode: 'KE', name: 'Kenya', phoneCode: '254' },
  { countryCode: 'KG', name: 'Kyrgyzstan', phoneCode: '996' },
  { countryCode: 'KH', name: 'Cambodia', phoneCode: '855' },
  { countryCode: 'KI', name: 'Kiribati', phoneCode: '686' },
  { countryCode: 'KM', name: 'Comoros', phoneCode: '269' },
  {
    countryCode: 'KN',
    name: 'Saint Kitts and Nevis',
    phoneCode: '1-869',
  },
  {
    countryCode: 'KP',
    name: "Korea, Democratic People's Republic of",
    phoneCode: '850',
  },
  { countryCode: 'KR', name: 'Korea, Republic of', phoneCode: '82' },
  { countryCode: 'KW', name: 'Kuwait', phoneCode: '965' },
  { countryCode: 'KY', name: 'Cayman Islands', phoneCode: '1-345' },
  { countryCode: 'KZ', name: 'Kazakhstan', phoneCode: '7' },
  {
    countryCode: 'LA',
    name: "Lao People's Democratic Republic",
    phoneCode: '856',
  },
  { countryCode: 'LB', name: 'Lebanon', phoneCode: '961' },
  { countryCode: 'LC', name: 'Saint Lucia', phoneCode: '1-758' },
  { countryCode: 'LI', name: 'Liechtenstein', phoneCode: '423' },
  { countryCode: 'LK', name: 'Sri Lanka', phoneCode: '94' },
  { countryCode: 'LR', name: 'Liberia', phoneCode: '231' },
  { countryCode: 'LS', name: 'Lesotho', phoneCode: '266' },
  { countryCode: 'LT', name: 'Lithuania', phoneCode: '370' },
  { countryCode: 'LU', name: 'Luxembourg', phoneCode: '352' },
  { countryCode: 'LV', name: 'Latvia', phoneCode: '371' },
  { countryCode: 'LY', name: 'Libya', phoneCode: '218' },
  { countryCode: 'MA', name: 'Morocco', phoneCode: '212' },
  { countryCode: 'MC', name: 'Monaco', phoneCode: '377' },
  {
    countryCode: 'MD',
    name: 'Moldova, Republic of',
    phoneCode: '373',
  },
  { countryCode: 'ME', name: 'Montenegro', phoneCode: '382' },
  {
    countryCode: 'MF',
    name: 'Saint Martin (French part)',
    phoneCode: '590',
  },
  { countryCode: 'MG', name: 'Madagascar', phoneCode: '261' },
  { countryCode: 'MH', name: 'Marshall Islands', phoneCode: '692' },
  {
    countryCode: 'MK',
    name: 'Macedonia, the Former Yugoslav Republic of',
    phoneCode: '389',
  },
  { countryCode: 'ML', name: 'Mali', phoneCode: '223' },
  { countryCode: 'MM', name: 'Myanmar', phoneCode: '95' },
  { countryCode: 'MN', name: 'Mongolia', phoneCode: '976' },
  { countryCode: 'MO', name: 'Macao', phoneCode: '853' },
  {
    countryCode: 'MP',
    name: 'Northern Mariana Islands',
    phoneCode: '1-670',
  },
  { countryCode: 'MQ', name: 'Martinique', phoneCode: '596' },
  { countryCode: 'MR', name: 'Mauritania', phoneCode: '222' },
  { countryCode: 'MS', name: 'Montserrat', phoneCode: '1-664' },
  { countryCode: 'MT', name: 'Malta', phoneCode: '356' },
  { countryCode: 'MU', name: 'Mauritius', phoneCode: '230' },
  { countryCode: 'MV', name: 'Maldives', phoneCode: '960' },
  { countryCode: 'MW', name: 'Malawi', phoneCode: '265' },
  { countryCode: 'MX', name: 'Mexico', phoneCode: '52' },
  { countryCode: 'MY', name: 'Malaysia', phoneCode: '60' },
  { countryCode: 'MZ', name: 'Mozambique', phoneCode: '258' },
  { countryCode: 'NA', name: 'Namibia', phoneCode: '264' },
  { countryCode: 'NC', name: 'New Caledonia', phoneCode: '687' },
  { countryCode: 'NE', name: 'Niger', phoneCode: '227' },
  { countryCode: 'NF', name: 'Norfolk Island', phoneCode: '672' },
  { countryCode: 'NG', name: 'Nigeria', phoneCode: '234' },
  { countryCode: 'NI', name: 'Nicaragua', phoneCode: '505' },
  { countryCode: 'NL', name: 'Netherlands', phoneCode: '31' },
  { countryCode: 'NO', name: 'Norway', phoneCode: '47' },
  { countryCode: 'NP', name: 'Nepal', phoneCode: '977' },
  { countryCode: 'NR', name: 'Nauru', phoneCode: '674' },
  { countryCode: 'NU', name: 'Niue', phoneCode: '683' },
  { countryCode: 'NZ', name: 'New Zealand', phoneCode: '64' },
  { countryCode: 'OM', name: 'Oman', phoneCode: '968' },
  { countryCode: 'PA', name: 'Panama', phoneCode: '507' },
  { countryCode: 'PE', name: 'Peru', phoneCode: '51' },
  { countryCode: 'PF', name: 'French Polynesia', phoneCode: '689' },
  { countryCode: 'PG', name: 'Papua New Guinea', phoneCode: '675' },
  { countryCode: 'PH', name: 'Philippines', phoneCode: '63' },
  { countryCode: 'PK', name: 'Pakistan', phoneCode: '92' },
  { countryCode: 'PL', name: 'Poland', phoneCode: '48' },
  {
    countryCode: 'PM',
    name: 'Saint Pierre and Miquelon',
    phoneCode: '508',
  },
  { countryCode: 'PN', name: 'Pitcairn', phoneCode: '870' },
  { countryCode: 'PR', name: 'Puerto Rico', phoneCode: '1' },
  {
    countryCode: 'PS',
    name: 'Palestine, State of',
    phoneCode: '970',
  },
  { countryCode: 'PT', name: 'Portugal', phoneCode: '351' },
  { countryCode: 'PW', name: 'Palau', phoneCode: '680' },
  { countryCode: 'PY', name: 'Paraguay', phoneCode: '595' },
  { countryCode: 'QA', name: 'Qatar', phoneCode: '974' },
  { countryCode: 'RE', name: 'Reunion', phoneCode: '262' },
  { countryCode: 'RO', name: 'Romania', phoneCode: '40' },
  { countryCode: 'RS', name: 'Serbia', phoneCode: '381' },
  { countryCode: 'RU', name: 'Russian Federation', phoneCode: '7' },
  { countryCode: 'RW', name: 'Rwanda', phoneCode: '250' },
  { countryCode: 'SA', name: 'Saudi Arabia', phoneCode: '966' },
  { countryCode: 'SB', name: 'Solomon Islands', phoneCode: '677' },
  { countryCode: 'SC', name: 'Seychelles', phoneCode: '248' },
  { countryCode: 'SD', name: 'Sudan', phoneCode: '249' },
  { countryCode: 'SE', name: 'Sweden', phoneCode: '46' },
  { countryCode: 'SG', name: 'Singapore', phoneCode: '65' },
  { countryCode: 'SH', name: 'Saint Helena', phoneCode: '290' },
  { countryCode: 'SI', name: 'Slovenia', phoneCode: '386' },
  {
    countryCode: 'SJ',
    name: 'Svalbard and Jan Mayen',
    phoneCode: '47',
  },
  { countryCode: 'SK', name: 'Slovakia', phoneCode: '421' },
  { countryCode: 'SL', name: 'Sierra Leone', phoneCode: '232' },
  { countryCode: 'SM', name: 'San Marino', phoneCode: '378' },
  { countryCode: 'SN', name: 'Senegal', phoneCode: '221' },
  { countryCode: 'SO', name: 'Somalia', phoneCode: '252' },
  { countryCode: 'SR', name: 'Suriname', phoneCode: '597' },
  { countryCode: 'SS', name: 'South Sudan', phoneCode: '211' },
  {
    countryCode: 'ST',
    name: 'Sao Tome and Principe',
    phoneCode: '239',
  },
  { countryCode: 'SV', name: 'El Salvador', phoneCode: '503' },
  {
    countryCode: 'SX',
    name: 'Sint Maarten (Dutch part)',
    phoneCode: '1-721',
  },
  {
    countryCode: 'SY',
    name: 'Syrian Arab Republic',
    phoneCode: '963',
  },
  { countryCode: 'SZ', name: 'Swaziland', phoneCode: '268' },
  {
    countryCode: 'TC',
    name: 'Turks and Caicos Islands',
    phoneCode: '1-649',
  },
  { countryCode: 'TD', name: 'Chad', phoneCode: '235' },
  {
    countryCode: 'TF',
    name: 'French Southern Territories',
    phoneCode: '262',
  },
  { countryCode: 'TG', name: 'Togo', phoneCode: '228' },
  { countryCode: 'TH', name: 'Thailand', phoneCode: '66' },
  { countryCode: 'TJ', name: 'Tajikistan', phoneCode: '992' },
  { countryCode: 'TK', name: 'Tokelau', phoneCode: '690' },
  { countryCode: 'TL', name: 'Timor-Leste', phoneCode: '670' },
  { countryCode: 'TM', name: 'Turkmenistan', phoneCode: '993' },
  { countryCode: 'TN', name: 'Tunisia', phoneCode: '216' },
  { countryCode: 'TO', name: 'Tonga', phoneCode: '676' },
  { countryCode: 'TR', name: 'Turkey', phoneCode: '90' },
  {
    countryCode: 'TT',
    name: 'Trinidad and Tobago',
    phoneCode: '1-868',
  },
  { countryCode: 'TV', name: 'Tuvalu', phoneCode: '688' },
  {
    countryCode: 'TW',
    name: 'Taiwan, Province of China',
    phoneCode: '886',
  },
  {
    countryCode: 'TZ',
    name: 'United Republic of Tanzania',
    phoneCode: '255',
  },
  { countryCode: 'UA', name: 'Ukraine', phoneCode: '380' },
  { countryCode: 'UG', name: 'Uganda', phoneCode: '256' },
  {
    countryCode: 'US',
    name: 'United States',
    phoneCode: '1',
  },
  { countryCode: 'UY', name: 'Uruguay', phoneCode: '598' },
  { countryCode: 'UZ', name: 'Uzbekistan', phoneCode: '998' },
  {
    countryCode: 'VA',
    name: 'Holy See (Vatican City State)',
    phoneCode: '379',
  },
  {
    countryCode: 'VC',
    name: 'Saint Vincent and the Grenadines',
    phoneCode: '1-784',
  },
  { countryCode: 'VE', name: 'Venezuela', phoneCode: '58' },
  {
    countryCode: 'VG',
    name: 'British Virgin Islands',
    phoneCode: '1-284',
  },
  {
    countryCode: 'VI',
    name: 'US Virgin Islands',
    phoneCode: '1-340',
  },
  { countryCode: 'VN', name: 'Vietnam', phoneCode: '84' },
  { countryCode: 'VU', name: 'Vanuatu', phoneCode: '678' },
  { countryCode: 'WF', name: 'Wallis and Futuna', phoneCode: '681' },
  { countryCode: 'WS', name: 'Samoa', phoneCode: '685' },
  { countryCode: 'XK', name: 'Kosovo', phoneCode: '383' },
  { countryCode: 'YE', name: 'Yemen', phoneCode: '967' },
  { countryCode: 'YT', name: 'Mayotte', phoneCode: '262' },
  { countryCode: 'ZA', name: 'South Africa', phoneCode: '27' },
  { countryCode: 'ZM', name: 'Zambia', phoneCode: '260' },
  { countryCode: 'ZW', name: 'Zimbabwe', phoneCode: '263' },
];

export const constants = {
    HOME: "home",
    ABOUT: "about",
    SUPPORT: "support",
    CONTACT: "contact",
    MOBILE_MONEY: "mobile_money",
    BANK_TRANSFER: "bank_transfer",
    CASH_PICKUP: "cash_pickup",

    FREE_OPERATOR_FEE: "FREE_OPERATOR_FEE",
    FIXED_AMOUNT: "FIXED_AMOUNT",
    FIXED_RATE: "FIXED_RATE",
    PERCENTAGE: "PERCENTAGE",
    TRANSFER_STATUS_PENDING_VERIFICATION: "PENDING_VERIFICATION",
    TRANSFER_STATUS_PENDING: "PENDING_PAYMENT",
    TRANSFER_STATUS_PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
    TRANSFER_STATUS_COMPLETE: "COMPLETE",
    TRANSFER_STATUS_CANCELLED: "CANCELLED",

    VERIFICATION_TYPE_DOCUMENT: "DOCUMENT",
    VERIFICATION_TYPE_IDENTITY: "IDENTITY",
    VERIFICATION_TYPE_DOCUMENT_WITH_IDENTITY_PRECURSOR: "DOCUMENT_WITH_IDENTITY_PRECURSOR",
    VERIFICATION_TYPE_WATCHLIST: "WATCHLIST",

    VERIFICATION_STAGE_FINAL: "FINAL",
    MOBILE: "MOBILE",
    DESKTOP: "DESKTOP",

    SIGNUP_COUNTRIES: {
        "AT": "Austria",
        "BE": "Belgium",
        "BG": "Bulgaria",
        "CA": "Canada",
        "HR": "Croatia",
        "CY": "Cyprus",
        "CZ": "Czech Republic",
        "DK": "Denmark",
        "EE": "Estonia",
        "FI": "Finland",
        "FR": "France",
        "DE": "Germany",
        "GR": "Greece",
        "HU": "Hungary",
        "IE": "Ireland",
        "IT": "Italy",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MT": "Malta",
        "NL": "Netherlands",
        "PL": "Poland",
        "PT": "Portugal",
        "RO": "Romania",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "ES": "Spain",
        "SE": "Sweden",
        "GB": "United Kingdom",
    },

    COUNTRIES_PHONE_CODES: countriesAndCodes
}



export const resources = {
    DICE_BEAR_USER: "https://avatars.dicebear.com/api/initials/",
    DICE_BEAR_RECIPIENT: "https://avatars.dicebear.com/api/initials/",
    TRUST_PAYMENT_URL: 'https://payments.securetrading.net/process/payments/choice'
}

export const days = Array.from(Array(31).keys())

export const months: any = {
    January: 1,
    February: 2,
    March: 3,
    April: 4,
    May: 5,
    June: 6,
    July: 7,
    August: 8,
    September: 9,
    October: 10,
    November: 11,
    December: 12,
}
