export const paths = {
    EN_LANDING: "/en/",
    CA_LANDING: "/ca/",
    LANDING: "/",
    SIGN_UP: "/sign-up",
    SIGN_IN: "/sign-in",
    CONFIRM_ACCOUNT_EMAIL: "/email/confirm-account",
    CONFIRM_ACCOUNT: "/confirm-account",
    PASSWORD_RESET_EMAIL : "/email/password-reset",
    RESET_PASSWORD: "/reset-password",
    DASHBOARD: "/dashboard",
    PROFILE: "/profile",
    EDIT_PROFILE: "/edit-profile",
    CHANGE_PASSWORD: "/change-password",
    TRANSFER_METHOD: "/transfer-method",
    GET_QUOTE: "/get-quote",
    VERIFICATION: "/verification",
    RECIPIENT: "/recipient",
    RECIPIENT_DETAILS: "/recipient-details",
    REVIEW: "/review",
    PAYMENT_METHOD: "/payment-method",
    CARD_PAYMENT: "/card-payment",
    CREATE_TRANSFER: "/create-transfer",
    TRANSFER_COMPLETE: "/transfer-complete",
    TRUELAYER_PROVIDERS: "/truelayer-providers",

    LEGAL: "/support/legal",
    SUPPORT: "/support",
    ABOUT: "/content/about",
    CONTACT: "/content/contact",

    NOT_FOUND : "/404",
}
