name: Deploy to Vercel Repo

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config user.email "sbdev@sukatebezeboh.com"
          git config user.name "Automated Deployment"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.VERCEL_SSH_FE }}

      - name: Add GitHub Remote
        run: git remote add deploy git@github.com:sukatebezeboh/sbremit-fe-vercel.git

      - name: Checkout to develop
        run: git checkout develop

      - name: Pull latest changes
        run: git pull deploy develop --no-rebase --allow-unrelated-histories

      - name: Push to GitHub
        run: git push deploy develop
