name: Deploy to Vercel Repo

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config user.email "sbdev@sukatebezeboh.com" 
          git config user.name "Automated Deployment"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.VERCEL_SSH_FE }}

      - name: Go mad
        run: |
          git clone git@github.com:sukatebezeboh/sbremit-fe-vercel.git
          cd sbremit-fe-vercel
          git remote add deploy git@github.com:sukatebezeboh/sbremit-fe-vercel.git
          git checkout develop
          git status
          git branch
          git remote -v
          git pull git@github.com:Sukate-Bezeboh/sbremit-fe.git develop --no-rebase
          git push deploy develop --force

      # - name: Checkout to develop
      #   run: git checkout origin/develop

      # - name: Check project name and repo link
      #   run: |
      #     echo "User name: $(git config --get user.name)"
      #     echo "Current repo link: $(git config --get remote.deploy.url)"
      #     echo "Current branch: $(git branch --show-current)"
      #     echo "Current commit: $(git rev-parse HEAD)"
      #     echo "Current commit message: $(git log -1 --pretty=%B)"
      #     echo "Current commit author: $(git log -1 --pretty=%aN)"
      #     echo "Current commit date: $(git log -1 --pretty=%aD)"
      #     echo "Versions: $(git remote -v)"
      #     echo "Status: $(git status)"

      # - name: Log
      #   run: git log --oneline --decorate --graph

      # - name: Pull latest changes
      #   run: git pull deploy develop --rebase --allow-unrelated-histories || true

      # - name: Commit conflict
      #   run: git commit -am "Commit conflict"

      # - name: Push to GitHub
      #   run: git push deploy develop --force
